### ISSUE TITLE
KeyError: 'scopes' when running

### ISSUE THREAD

**Issue by RubenGarcia** [Arello-Mobile/swagger2rst#9]
```
$ python3 -m swg2rst.swagger2rst swagger.yaml 
/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger2rst.py:74: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  doc = yaml.load(_file)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger2rst.py", line 127, in <module>
    main()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger2rst.py", line 51, in main
    swagger_doc = doc_module.SwaggerObject(doc, examples=examples)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger/base_swagger_object.py", line 74, in __init__
    self._fill_security_definitions(obj)
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger/base_swagger_object.py", line 146, in _fill_security_definitions
    name: SecurityDefinition(name, _obj) for name, _obj in obj['securityDefinitions'].items()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger/base_swagger_object.py", line 146, in <dictcomp>
    name: SecurityDefinition(name, _obj) for name, _obj in obj['securityDefinitions'].items()
  File "/home/rgarcia/.local/lib/python3.6/site-packages/swg2rst/swagger/security_definition.py", line 36, in __init__
    self.scopes = obj['scopes']
KeyError: 'scopes'
```

**Comment by RubenGarcia** [comment]
Also, the project was not updated in a few years, and the installation instructions do not put an executable in the path.
Can the README of this project be changed to indicate that this code no longer works in latest python?
Is there a recommended substitute for this software?
